---
- name: "Ensure required parameter(s) are provided."
  ansible.builtin.assert:
    that:
      - downstream_project is defined
    quiet: True
    fail_msg: "Missing required parameter(s)."

- name: "Ensure downtream project folder {{ downstream_project }} exists."
  ansible.builtin.file:
    path: "{{ downstream_project }}"
    state: directory

- name: "Copy all files from {{ project_root_folder }} to {{ downstream_project }}"
  ansible.builtin.include_tasks: copy_upstream_collection.yml
  vars:
    src: "{{ project_root_folder }}"
    dest: "{{ downstream_project }}"

- name: "Delete .github folders in {{ downstream_project }}."
  ansible.builtin.include_tasks: remove_from_collection.yml
  vars:
    file_to_remove: "{{ item }}"
  loop:
    - "{{ downstream_project }}/.github"

- ansible.builtin.include_tasks: docs/rename_name_and_namespace.yml
  vars:
    path_to_file: "{{ item }}"
  loop:
    - "{{ downstream_project }}/README.md"
    - "{{ downstream_project }}/CHANGELOG.rst"
    - "{{ downstream_project }}/requirements.yml"
