---
- ansible.builtin.include_tasks: utils/check_required_parameters.yml

- ansible.builtin.include_tasks: utils/check_dir_exists.yml
  vars:
    path_to_dir: "{{ project_root_folder }}"

- ansible.builtin.include_tasks: collection_skeleton.yml

- ansible.builtin.include_tasks: roles/update_galaxy_yml.yml

- ansible.builtin.include_tasks: docs/main.yml
  vars:
    path_to_docs_folder: "{{ downstream_project }}/docs"

- ansible.builtin.include_tasks: roles/main.yml

- ansible.builtin.include_tasks: playbooks/main.yml

- ansible.builtin.include_tasks: molecule.yml
  vars:
    molecule_dir: "{{ downstream_project }}/molecule"
