---
upstream_name:
downstream_name:
upstream_collection_name: "{{ upstream_name }}"
project_git_url:
project_git_version:
upstream_namespace: middleware_automation
downstream_namespace: redhat
workdir: "{{ lookup('env', 'PWD') }}"
upstream_organisation: 'ansible-middleware'
upstream_projects_dir: "{{ workdir }}/upstream"
downstream_projects_dir: "{{ workdir }}/downstream"
skip_setup: True
post_processors_replacements: []
# maps internal dependencies that were processed by raft
upstream_downstream_collections_map:
  - { upstream_name: 'middleware_automation.redhat_csp_download', downstream_name: 'redhat.redhat_csp_download' }
  - { upstream_name: 'middleware_automation.jws', downstream_name: 'redhat.jws' }
  - { upstream_name: 'middleware_automation.wildfly', downstream_name: 'redhat.eap' }
  - { upstream_name: 'middleware_automation.infinispan', downstream_name: 'redhat.data_grid' }
  - { upstream_name: 'middleware_automation.keycloak', downstream_name: 'redhat.sso' }
  - { upstream_name: 'middleware_automation.amq', downstream_name: 'redhat.amq_broker' }
  - { upstream_name: 'middleware_automation.amq_streams', downstream_name: 'redhat.amq_streams' }
  - { upstream_name: 'middleware_automation.common', downstream_name: 'redhat.runtimes_common' }
# anything inside <!--start {{ downstream_placeholder_delete }} --> and <!--end {{ downstream_placeholder_delete }} --> will be removed
downstream_placeholder_:
# anything inside <!--start {{ downstream_placeholder_content }} --> and <!--end {{ downstream_placeholder_content }} --> will be replaced with content
downstream_placeholder_content:
  - placeholder: support
    content: |
      ## Support
      
      {{ downstream_name }} collection v{{ downstream_version }} is a Beta release and for [Technical Preview](https://access.redhat.com/support/offerings/techpreview).
      If you have any issues or questions related to collection, please don't hesitate to contact us on Ansible-middleware-core@redhat.com or open an issue on 
      https://github.com/ansible-middleware/{{ upstream_name }/issues
  - placeholder: rhn_credentials
    content: |
      ## Downloading from the Customer Portal

      The `{{ downstream_name }}` role supports downloading and installing from the Red Hat Customer Portal, when the following variables are defined:
      ```
      rhn_username{{':'}} '<customer_portal_username>'
      rhn_password{{':'}} '<customer_portal_password>'
      ```
