---
- import_playbook: ./janus.yml
  vars:
    post_processors_replacements:
      - match: "amq_broker[.]xsd"
        replace: "activemq.xsd"
      - match: "org[.]apache[.]amq_broker[.]"
        replace: "org.apache.activemq."
      - match: "hawtio[.]realm=amq_broker"
        replace: "hawtio.realm=activemq"
        file: '[.]yml$'
      - match: "amq_broker[.]org"
        replace: "activemq.org"
      - match: "redhat[.]amq(?!_broker)"
        replace: "redhat.amq_broker"
      - match: "urn:amq_broker"
        replace: "urn:activemq"
      - match: "- amq_broker"
        replace: "- activemq"
        file: "main.yml$"
      - match: "amq_broker[.]apache[.]org"
        replace: "activemq.apache.org"
        file: "README.md$"
