---
- ansible.builtin.import_playbook: community.fqcn_migration.fqcn_migration
  vars:
    upstream_name: wildfly
    downstream_name: eap
    downstream_namespace: 'redhat'
    upstream_namespace: 'middleware_automation'
    project_git_url: "{{ lookup('env', 'GIT_REPOSITORY_URL') | default('https://github.com/ansible-middleware/wildfly.git', true) }}"
    project_git_version: "{{ lookup('env', 'GIT_REPOSITORY_BRANCH') | default('main', true) }}"
    case_insensitive_match: true

    upstream_downstream_collections_map:
      - { upstream_name: 'middleware_automation.common', downstream_name: 'redhat.runtimes_common' }
      - { upstream_name: 'middleware_automation.wildfly', downstream_name: 'redhat.eap' }

    post_processors_replacements:
     - match: "eap[.]statistics-enabled"
       replace: "wildfly.statistics-enabled"
     - match: "eap-configuration:"
       replace: "wildfly-configuration:"
       file: 'molecule.*j2$'
     - match: "repo1.maven.org/maven2/org/eap/prospero"
       replace: "repo1.maven.org/maven2/org/wildfly/prospero"
     - match: "files/wildfly-custom.xml"
       replace: "files/eap-custom.xml"
       file: 'molecule.*yml$'
     - match: "https://github.com/rpelisse/eap-quickstarts/releases/download/kitchensink_eap31_1.0/kitchensink.war"
       replace: "https://github.com/rpelisse/wildfly-quickstarts/releases/download/kitchensink_wildfly26_1.0/kitchensink.war"
       file: 'molecule.*yml$'
     - match: "https://github.com/rpelisse/simple-servlet/releases/download/info_wfly31_1.2/info-1.2.war"
       replace: "https://github.com/rpelisse/simple-servlet/releases/download/info_eap7.4_1.0/info-1.0.war"
       file: 'molecule.*yml$'
     - match: "[/]github.com[/]ansible-middleware[/]eap"
       replace: "/github.com/ansible-middleware/wildfly"
       file: "CHANGELOG.md$"
    galaxy:
      documentation: https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform
      homepage: https://access.redhat.com/products/red-hat-jboss-enterprise-application-platform
    # anything inside <!--start {{ <downstream_placeholder>_delete }} --> and <!--end {{ <downstream_placeholder>_delete }} --> will be removed
    excluded_roles_from_downstream:
      - roles/wildfly_subs
    downstream_placeholder_delete:
      - build_status
    # anything inside <!--start {{ <downstream_placeholder>_content }} --> and <!--end {{ <downstream_placeholder>_content }} --> will be replaced with content
    downstream_placeholder_content:
      - placeholder: roles_paths
        content: |

      - placeholder: galaxy_download
        content: |
          ### Installing the Collection from Automation Hub

          Before using the collection, you need to setup Ansible Automation Hub as galaxy server; then install it via the CLI:

              ansible-galaxy collection install redhat.eap
      - placeholder: support
        content: |
          ## Support

          The redhat.eap collection v{{ galaxy_version | default('0.0.0-dev') }} is released as the [Red Hat Ansible certified content
          collection for Red Hat JBoss Enterprise Application Platform](https://console.redhat.com/ansible/automation-hub/repo/published/redhat/eap) with
          [Production Support](https://access.redhat.com/support/offerings/production).
          If you have any issues or questions related to this collection, please contact support at [Red Hat Customer
          Experience & Engagement](https://access.redhat.com/support/). Alternatively contact the community by opening
          an issue at https://github.com/ansible-middleware/wildfly/issues.

          For more information about using this collection, see [Installing JBoss EAP by using the Red Hat Ansible Certified Content
          Collection](https://docs.redhat.com/en/documentation/red_hat_jboss_enterprise_application_platform/7.4/html/installing_jboss_eap_by_using_the_red_hat_ansible_certified_content_collection/index).
      - placeholder: rhn_credentials
        content: |
          ## Downloading products from the Customer Portal

          The `redhat.eap.eap_install` role supports downloading and installing from the Red Hat Customer Portal using credentials associated to a service account. After
          login in the customer portal and navigating to the hybrid cloud console, select the [services account tab](https://console.redhat.com/application-services/service-accounts)
          to create one, if needed. Client ID and Client secret associated to the service account needs to be provided with the following variables are defined:
          ```
          rhn_username{{':'}} '<client_id>'
          rhn_password{{':'}} '<client_secret>'
          ```

          The downloaded product archive will be stored in the controller working directory, and then distributed to target nodes.

          When patching is requested, via the `eap_apply_cp` variable, the most recently published cumulative patch will be installed; to use a specific patch version instead,
          set it with the `eap_patch_version` variable.

          NOTE: downgrading patches is not supported.
