---
- ansible.builtin.import_playbook: community.fqcn_migration.fqcn_migration
  vars:
    upstream_name: jbcs
    downstream_name: jbcs
    downstream_namespace: 'redhat'
    upstream_namespace: 'middleware_automation'
    project_git_url: https://github.com/ansible-middleware/jbcs.git
    project_git_version: main
    upstream_downstream_collections_map:
      - { upstream_name: 'middleware_automation.common', downstream_name: 'redhat.runtimes_common' }
      - { upstream_name: 'middleware_automation.jbcs', downstream_name: 'redhat.jbcs' }
    galaxy:
      documentation: https://access.redhat.com/documentation/en-us/red_hat_jboss_core_services
      homepage: https://access.redhat.com/documentation/en-us/red_hat_jboss_core_services/2.4.57
