---
- import_playbook: ../janus.yml
  vars:
    upstream_name: jws
    downstream_name: "{{ upstream_name }}"
    project_git_url: "https://github.com/ansible-middleware/jws.git"
    project_git_version: "ISSUE_167"
