---
- ansible.builtin.import_playbook: community.fqcn_migration.fqcn_migration
  vars:
    upstream_name: jws
    downstream_name: jws
    downstream_namespace: 'redhat'
    upstream_namespace: 'middleware_automation'
    project_git_url: "{{ lookup('env', 'GIT_REPOSITORY_URL') | default('https://github.com/ansible-middleware/jws.git', true) }}"
    project_git_version: "{{ lookup('env', 'GIT_REPOSITORY_BRANCH') | default('main', true) }}"
    gitdescribe_galaxy_version: "{{ true if lookup('env', 'RELEASE_NAME') == '' else false }}"
    upstream_downstream_collections_map:
      - { upstream_name: 'middleware_automation.common', downstream_name: 'redhat.runtimes_common' }
      - { upstream_name: 'middleware_automation.jws', downstream_name: 'redhat.jws' }
    post_processors_replacements:
     - match: "the native archive file .by default, `False`"
       replace: "the native archive file (by default, `True`"
       file: 'README.md'
    galaxy:
      documentation: https://access.redhat.com/documentation/en-us/red_hat_jboss_web_server
      homepage: https://access.redhat.com/products/red-hat-jboss-web-server
    # anything inside <!--start {{ <downstream_placeholder>_delete }} --> and <!--end {{ <downstream_placeholder>_delete }} --> will be removed
    downstream_placeholder_delete:
      - build_status
    # anything inside <!--start {{ <downstream_placeholder>_content }} --> and <!--end {{ <downstream_placeholder>_content }} --> will be replaced with content
    downstream_placeholder_content:
      - placeholder: no_native_upstream
        content: |

      - placeholder: ansible_version
        content: |
          Red Hat supports the most recent version of redhat.jws collection on Ansible Automation Platform 2.5 / ansible-core 2.16.

          The collection is continuously tested on Ansible version 2.14 or later. Red Hat might test the plug-ins and modules that are within a collection
          with specific Ansible versions only. A collection can contain metadata that identifies these Ansible versions, and a warning message will
          be printed if the collection is executed on not supported versions of Ansible.
      - placeholder: galaxy_download
        content: |
          For demonstration purposes, you can run the collection directly from this folder. However, the proper setup is to download and install the collection from the Red Hat Automation Hub.

          Before you install the collection, you must ensure that your system complies with the following prerequisites:
            - You have installed the ansible-core package version 2.14 or later on a control node in your system by installing Red Hat Ansible Automation Platform 2.x.
            - You have updated the ansible.cfg file to use the Red Hat Automation Hub as your *primary source* of Ansible collections.
          You can install the collection on your Ansible control node by using the following command:
              $ ansible-galaxy collection install redhat.jws
      - placeholder: support
        content: |
          The redhat.jws collection v{{ galaxy_version | default('0.0.0-dev') }} is released as the [Red Hat Ansible certified content collection for JBoss Web Server](https://console.redhat.com/ansible/automation-hub/repo/published/redhat/jws) with [Production Support](https://access.redhat.com/support/offerings/production).
          If you have any issues or questions related to this collection, please contact support at [Red Hat Customer Experience & Engagement](https://access.redhat.com/support/). Alternatively
          contact the community by opening an issue at https://github.com/ansible-middleware/jws/issues.

          For more information about using this collection, see [Installing JBoss Web Server by using the Red Hat Ansible Certified Content Collection](https://access.redhat.com/documentation/en-us/red_hat_jboss_web_server/6.0/html-single/installing_jboss_web_server_by_using_the_red_hat_ansible_certified_content_collection/index).
      - placeholder: rhn_credentials
        content: |
          #### Downloading from the Customer Portal

          The `redhat.jws.jws` role supports downloading and installing from the Red Hat Customer Portal using credentials associated to a service account. After
          login in the customer portal and navigating to the hybrid cloud console, select the [services account tab](https://console.redhat.com/application-services/service-accounts)
          to create one, if needed. Client ID and Client secret associated to the service account needs to be provided with the following variables are defined:
          ```
          rhn_username{{':'}} '<client_id>'
          rhn_password{{':'}} '<client_secret>'
          ```

          The downloaded product archive will be stored in the controller working directory, and then distributed to target nodes.
