---
- ansible.builtin.import_playbook: community.fqcn_migration.fqcn_migration
  vars:
    upstream_name: common
    downstream_name: runtimes_common
    downstream_namespace: 'redhat'
    upstream_namespace: 'middleware_automation'
    project_git_url: "https://github.com/ansible-middleware/{{ upstream_name }}.git"
    project_git_version: main
    upstream_downstream_collections_map:
      - { upstream_name: 'middleware_automation.common', downstream_name: 'redhat.runtimes_common' }
    post_processors_replacements:
      - match: "add_file_runtimes_common_args"
        replace: "add_file_common_args"
      - match: "load_file_runtimes_common_arguments"
        replace: "load_file_common_arguments"
      - match: "ansible[.]module_utils[.]runtimes_common"
        replace: "ansible.module_utils.common"
    # anything inside <!--start {{ <downstream_placeholder>_delete }} --> and <!--end {{ <downstream_placeholder>_delete }} --> will be removed
    downstream_placeholder_delete:
      - build_status
    # anything inside <!--start {{ <downstream_placeholder>_content }} --> and <!--end {{ <downstream_placeholder>_content }} --> will be replaced with content
    downstream_placeholder_content:
      - placeholder: galaxy_download
        content: |
          ### Installing the Collection from Automation Hub

          Before using the collection, you need to setup Ansible Automation Hub as galaxy server; then install it via the CLI:

              ansible-galaxy collection install redhat.runtimes_common
      - placeholder: support
        content: |
          ## Support
          
          redhat.runtimes_common collection v{{ galaxy_version | default('0.0.0-dev') }} is for [Technical Preview](https://access.redhat.com/support/offerings/techpreview).
          If you have any issues or questions related to collection, please don't hesitate to contact us on <Ansible-middleware-core@redhat.com> or open an issue on 
          <https://github.com/ansible-middleware/common/issues>
